"use strict";this.default_ContributorTargetingClientJs=this.default_ContributorTargetingClientJs||{};(function(_){var window=this;
try{
var aa=function(a){for(;a&&"."===a[0];)a=a.substring(1);return a},ca=function(a,b,c){a=a instanceof m?new m(a):new m(a,void 0);var d=a.c+"/",e=b;null===e&&(e=new ba);b=n(e,1)?n(e,1):"";e=n(e,2)?n(e,2):"";if(b.includes(":D:"))throw Error("l`"+b);a.c=d+(b+(""===e?"":":D:"+e))+"/"+c;return a},da=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},ea=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:da(a)}},
fa="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},ha;if("function"==typeof Object.setPrototypeOf)ha=Object.setPrototypeOf;else{var ia;a:{var ja={T:!0},ka={};try{ka.__proto__=ja;ia=ka.T;break a}catch(a){}ia=!1}ha=ia?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError("a`"+a);return a}:null}
var la=ha,ma=function(a,b){a.prototype=fa(b.prototype);a.prototype.constructor=a;if(la)la(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.F=b.prototype},na="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},q="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:
this,oa=function(a,b){if(b){var c=q;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&na(c,a,{configurable:!0,writable:!0,value:b})}},pa=function(){pa=function(){};q.Symbol||(q.Symbol=qa)},ra=function(a,b){this.a=a;na(this,"description",{configurable:!0,writable:!0,value:b})};ra.prototype.toString=function(){return this.a};
var qa=function(){function a(c){if(this instanceof a)throw new TypeError("d");return new ra("jscomp_symbol_"+(c||"")+"_"+b++,c)}var b=0;return a}(),ta=function(){pa();var a=q.Symbol.iterator;a||(a=q.Symbol.iterator=q.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&na(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return sa(da(this))}});ta=function(){}},sa=function(a){ta();a={next:a};a[q.Symbol.iterator]=function(){return this};return a},ua=function(a,b){ta();a instanceof
String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};oa("Array.prototype.keys",function(a){return a?a:function(){return ua(this,function(b){return b})}});
oa("String.prototype.includes",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("b`includes");if(b instanceof RegExp)throw new TypeError("c`includes");return-1!==this.indexOf(b,c||0)}});oa("Array.prototype.values",function(a){return a?a:function(){return ua(this,function(b,c){return c})}});
var va=va||{},r=this||self,t=function(a){return"string"==typeof a},wa=function(){},xa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&
"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},u=function(a){return"array"==xa(a)},ya=function(a){var b=xa(a);return"array"==b||"object"==b&&"number"==typeof a.length},za=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},Aa="closure_uid_"+(1E9*Math.random()>>>0),Ba=0,Ca=function(a,b,c){return a.call.apply(a.bind,arguments)},Da=function(a,b,
c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}},v=function(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?v=Ca:v=Da;return v.apply(null,arguments)},Ea=Date.now||function(){return+new Date},w=function(a,b){function c(){}c.prototype=b.prototype;a.F=
b.prototype;a.prototype=new c;a.prototype.constructor=a},Fa=function(a){return a},Ga=function(a){var b=null,c=r.trustedTypes||r.TrustedTypes;if(!c||!c.createPolicy)return b;try{b=c.createPolicy(a,{createHTML:Fa,createScript:Fa,createScriptURL:Fa,createURL:Fa})}catch(d){r.console&&r.console.error(d.message)}return b};Ga("ContributorTargetingClientJs#base");
var y=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,y);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};w(y,Error);y.prototype.name="CustomError";
var Ha;
var Ia=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(t(a))return t(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ja=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=t(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},La=function(a){a:{var b=Ka;for(var c=a.length,d=t(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,
d[e],e,a)){b=e;break a}b=-1}return 0>b?null:t(a)?a.charAt(b):a[b]},Ma=function(a,b){b=Ia(a,b);var c;(c=0<=b)&&Array.prototype.splice.call(a,b,1);return c},Na=function(a){return Array.prototype.concat.apply([],arguments)},Oa=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},Pa=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(ya(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var g=0;g<f;g++)a[e+g]=d[g]}else a.push(d)}},z=function(a,
b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)},Qa=function(a,b){for(var c=[],d=0;d<b;d++)c[d]=a;return c},Ra=function(a){for(var b=[],c=0;c<arguments.length;c++){var d=arguments[c];if(u(d))for(var e=0;e<d.length;e+=8192)for(var f=Ra.apply(null,z(d,e,e+8192)),g=0;g<f.length;g++)b.push(f[g]);else b.push(d)}return b};
var Sa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),Ta=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Sa.length;f++)c=Sa[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
var A=Ga("ContributorTargetingClientJs#html");
A&&A.createScript("");
var Ua=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]},Va=function(a,b){return a<b?-1:a>b?1:0};
A&&A.createURL("about:blank");
var B;a:{var Wa=r.navigator;if(Wa){var Xa=Wa.userAgent;if(Xa){B=Xa;break a}}B=""}var C=function(a){return-1!=B.indexOf(a)};
var Ya=function(){this.a=""},Za=function(a){(new Ya).a=A?A.createHTML(a):a};Za("<!DOCTYPE html>");Za("");Za("<br>");
var $a=function(a){var b=t(void 0)?"undefined".replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"):"\\s";return a.replace(new RegExp("(^"+(b?"|["+b+"]+":"")+")([a-z])","g"),function(c,d,e){return d+e.toUpperCase()})};
var ab=function(a){ab[" "](a);return a};ab[" "]=wa;var cb=function(a,b){var c=bb;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};
var db=C("Opera"),D=C("Trident")||C("MSIE"),eb=C("Edge"),fb=C("Gecko")&&!(-1!=B.toLowerCase().indexOf("webkit")&&!C("Edge"))&&!(C("Trident")||C("MSIE"))&&!C("Edge"),gb=-1!=B.toLowerCase().indexOf("webkit")&&!C("Edge"),hb=function(){var a=r.document;return a?a.documentMode:void 0},ib;
a:{var jb="",kb=function(){var a=B;if(fb)return/rv:([^\);]+)(\)|;)/.exec(a);if(eb)return/Edge\/([\d\.]+)/.exec(a);if(D)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(gb)return/WebKit\/(\S+)/.exec(a);if(db)return/(?:Version)[ \/]?(\S+)/.exec(a)}();kb&&(jb=kb?kb[1]:"");if(D){var lb=hb();if(null!=lb&&lb>parseFloat(jb)){ib=String(lb);break a}}ib=jb}
var mb=ib,bb={},nb=function(a){return cb(a,function(){for(var b=0,c=Ua(String(mb)).split("."),d=Ua(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"";do{g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==g[0].length&&0==h[0].length)break;b=Va(0==g[1].length?0:parseInt(g[1],10),0==h[1].length?0:parseInt(h[1],10))||Va(0==g[2].length,0==h[2].length)||Va(g[2],h[2]);g=g[3];h=h[3]}while(0==b)}return 0<=b})},ob;
ob=r.document&&D?hb():void 0;
var pb=C("Safari")&&!((C("Chrome")||C("CriOS"))&&!C("Edge")||C("Coast")||C("Opera")||C("Edge")||C("Edg/")||C("OPR")||C("Firefox")||C("FxiOS")||C("Silk")||C("Android"))&&!(C("iPhone")&&!C("iPod")&&!C("iPad")||C("iPad")||C("iPod"));
var qb=null,rb=fb||gb&&!pb||db||!pb&&!D&&"function"==typeof r.atob,tb=function(a){if(rb)return r.atob(a);var b="";sb(a,function(c){b+=String.fromCharCode(c)});return b},ub=function(a){var b=[];sb(a,function(c){b.push(c)});return b},sb=function(a,b){function c(k){for(;d<a.length;){var l=a.charAt(d++),p=qb[l];if(null!=p)return p;if(!/^[\s\xa0]*$/.test(l))throw Error("e`"+l);}return k}vb();for(var d=0;;){var e=c(-1),f=c(0),g=c(64),h=c(64);if(64===h&&-1===e)break;b(e<<2|f>>4);64!=g&&(b(f<<4&240|g>>2),
64!=h&&b(g<<6&192|h))}},vb=function(){if(!qb){qb={};for(var a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),b=["+/=","+/","-_=","-_.","-_"],c=0;5>c;c++)for(var d=a.concat(b[c].split("")),e=0;e<d.length;e++){var f=d[e];void 0===qb[f]&&(qb[f]=e)}}};
var E=function(a){var b=ba;this.b=a;this.f=b;this.a={};this.c=!0;if(0<this.b.length){for(a=0;a<this.b.length;a++){b=this.b[a];var c=b[0];this.a[c.toString()]=new wb(c,b[1])}this.c=!0}};E.prototype.w=function(){if(this.c){if(this.f){var a=this.a,b;for(b in a)if(Object.prototype.hasOwnProperty.call(a,b)){var c=a[b].a;c&&c.w()}}}else{this.b.length=0;a=G(this);a.sort();for(b=0;b<a.length;b++){var d=this.a[a[b]];(c=d.a)&&c.w();this.b.push([d.key,d.value])}this.c=!0}return this.b};
var xb=function(a){this.a=0;this.b=a};xb.prototype.next=function(){return this.a<this.b.length?{done:!1,value:this.b[this.a++]}:{done:!0,value:void 0}};"undefined"!=typeof Symbol&&(xb.prototype[Symbol.iterator]=function(){return this});var yb=function(a){var b=[],c=G(a);c.sort();for(var d=0;d<c.length;d++){var e=a.a[c[d]];b.push([e.key,e.value])}return b};E.prototype.entries=function(){var a=[],b=G(this);b.sort();for(var c=0;c<b.length;c++){var d=this.a[b[c]];a.push([d.key,zb(this,d)])}return new xb(a)};
E.prototype.keys=function(){var a=[],b=G(this);b.sort();for(var c=0;c<b.length;c++)a.push(this.a[b[c]].key);return new xb(a)};E.prototype.values=function(){var a=[],b=G(this);b.sort();for(var c=0;c<b.length;c++)a.push(zb(this,this.a[b[c]]));return new xb(a)};E.prototype.forEach=function(a,b){var c=G(this);c.sort();for(var d=0;d<c.length;d++){var e=this.a[c[d]];a.call(b,zb(this,e),e.key,this)}};
E.prototype.set=function(a,b){var c=new wb(a);this.f?(c.a=b,c.value=b.w()):c.value=b;this.a[a.toString()]=c;this.c=!1;return this};var zb=function(a,b){return a.f?(b.a||(b.a=new a.f(b.value)),b.a):b.value};E.prototype.get=function(a){if(a=this.a[a.toString()])return zb(this,a)};E.prototype.has=function(a){return a.toString()in this.a};var G=function(a){a=a.a;var b=[],c;for(c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.push(c);return b},wb=function(a,b){this.key=a;this.value=b;this.a=void 0};
var H=function(){},Ab="function"==typeof Uint8Array,Db=function(a,b,c){a.a=null;b||(b=[]);a.i=void 0;a.f=-1;a.b=b;a:{if(b=a.b.length){--b;var d=a.b[b];if(!(null===d||"object"!=typeof d||u(d)||Ab&&d instanceof Uint8Array)){a.g=b-a.f;a.c=d;break a}}a.g=Number.MAX_VALUE}a.h={};if(c)for(b=0;b<c.length;b++)d=c[b],d<a.g?(d+=a.f,a.b[d]=a.b[d]||Bb):(Cb(a),a.c[d]=a.c[d]||Bb)},Bb=[],Cb=function(a){var b=a.g+a.f;a.b[b]||(a.c=a.b[b]={})},n=function(a,b){if(b<a.g){b+=a.f;var c=a.b[b];return c===Bb?a.b[b]=[]:c}if(a.c)return c=
a.c[b],c===Bb?a.c[b]=[]:c},Eb=function(a,b,c){a.a||(a.a={});if(!a.a[c]){var d=n(a,c);d&&(a.a[c]=new b(d))}return a.a[c]},Gb=function(a){var b=Fb;a.a||(a.a={});if(!a.a[1]){for(var c=n(a,1),d=[],e=0;e<c.length;e++)d[e]=new b(c[e]);a.a[1]=d}b=a.a[1];b==Bb&&(b=a.a[1]=[]);return b},Hb=function(a){if(a.a)for(var b in a.a){var c=a.a[b];if(u(c))for(var d=0;d<c.length;d++)c[d]&&c[d].w();else c&&c.w()}};H.prototype.w=function(){Hb(this);return this.b};H.prototype.toString=function(){Hb(this);return this.b.toString()};
var Ib=function(a){Db(this,a,null)};w(Ib,H);
var Jb=function(){this.b=-1};
var Kb=function(){this.b=64;this.a=[];this.j=[];this.l=[];this.i=[];this.i[0]=128;for(var a=1;a<this.b;++a)this.i[a]=0;this.h=this.f=0;this.reset()};w(Kb,Jb);Kb.prototype.reset=function(){this.a[0]=1732584193;this.a[1]=4023233417;this.a[2]=2562383102;this.a[3]=271733878;this.a[4]=3285377520;this.h=this.f=0};
var Lb=function(a,b,c){c||(c=0);var d=a.l;if(t(b))for(var e=0;16>e;e++)d[e]=b.charCodeAt(c)<<24|b.charCodeAt(c+1)<<16|b.charCodeAt(c+2)<<8|b.charCodeAt(c+3),c+=4;else for(e=0;16>e;e++)d[e]=b[c]<<24|b[c+1]<<16|b[c+2]<<8|b[c+3],c+=4;for(e=16;80>e;e++){var f=d[e-3]^d[e-8]^d[e-14]^d[e-16];d[e]=(f<<1|f>>>31)&4294967295}b=a.a[0];c=a.a[1];var g=a.a[2],h=a.a[3],k=a.a[4];for(e=0;80>e;e++){if(40>e)if(20>e){f=h^c&(g^h);var l=1518500249}else f=c^g^h,l=1859775393;else 60>e?(f=c&g|h&(c|g),l=2400959708):(f=c^g^
h,l=3395469782);f=(b<<5|b>>>27)+f+k+l+d[e]&4294967295;k=h;h=g;g=(c<<30|c>>>2)&4294967295;c=b;b=f}a.a[0]=a.a[0]+b&4294967295;a.a[1]=a.a[1]+c&4294967295;a.a[2]=a.a[2]+g&4294967295;a.a[3]=a.a[3]+h&4294967295;a.a[4]=a.a[4]+k&4294967295};
Kb.prototype.c=function(a,b){if(null!=a){void 0===b&&(b=a.length);for(var c=b-this.b,d=0,e=this.j,f=this.f;d<b;){if(0==f)for(;d<=c;)Lb(this,a,d),d+=this.b;if(t(a))for(;d<b;){if(e[f]=a.charCodeAt(d),++f,++d,f==this.b){Lb(this,e);f=0;break}}else for(;d<b;)if(e[f]=a[d],++f,++d,f==this.b){Lb(this,e);f=0;break}}this.f=f;this.h+=b}};
Kb.prototype.g=function(){var a=[],b=8*this.h;56>this.f?this.c(this.i,56-this.f):this.c(this.i,this.b-(this.f-56));for(var c=this.b-1;56<=c;c--)this.j[c]=b&255,b/=256;Lb(this,this.j);for(c=b=0;5>c;c++)for(var d=24;0<=d;d-=8)a[b]=this.a[c]>>d&255,++b;return a};
var I=function(a,b){this.b=a|0;this.a=b|0},Pb=function(a){return 0<a?0x7fffffffffffffff<=a?Mb:new I(a,a/4294967296):0>a?-9223372036854775808>=a?Nb:J(new I(-a,-a/4294967296)):Ob},K=function(a,b){return new I(a,b)},Ob=K(0,0),Qb=K(1,0),Rb=K(-1,-1),Mb=K(4294967295,2147483647),Nb=K(0,2147483648),Sb=function(a){return 4294967296*a.a+(a.b>>>0)};
I.prototype.toString=function(a){a=a||10;if(2>a||36<a)throw Error("f`"+a);var b=this.a>>21;if(0==b||-1==b&&(0!=this.b||-2097152!=this.a))return b=Sb(this),10==a?""+b:b.toString(a);b=14-(a>>2);var c=Math.pow(a,b),d=K(c,c/4294967296);c=L(this,d);d=Math.abs(Sb(this.add(J(Tb(c,d)))));var e=10==a?""+d:d.toString(a);e.length<b&&(e="0000000000000".substr(e.length-b)+e);d=Sb(c);return(10==a?d:d.toString(a))+e};
var Ub=function(a){return 0==a.b&&0==a.a},M=function(a,b){return a.b==b.b&&a.a==b.a},Vb=function(a,b){return a.a==b.a?a.b==b.b?0:a.b>>>0>b.b>>>0?1:-1:a.a>b.a?1:-1},J=function(a){var b=~a.b+1|0;return K(b,~a.a+!b|0)};I.prototype.add=function(a){var b=this.a>>>16,c=this.a&65535,d=this.b>>>16,e=a.a>>>16,f=a.a&65535,g=a.b>>>16;a=(this.b&65535)+(a.b&65535);g=(a>>>16)+(d+g);d=g>>>16;d+=c+f;b=(d>>>16)+(b+e)&65535;return K((g&65535)<<16|a&65535,b<<16|d&65535)};
var Tb=function(a,b){if(Ub(a))return a;if(Ub(b))return b;var c=a.a>>>16,d=a.a&65535,e=a.b>>>16;a=a.b&65535;var f=b.a>>>16,g=b.a&65535,h=b.b>>>16;b=b.b&65535;var k=a*b;var l=(k>>>16)+e*b;var p=l>>>16;l=(l&65535)+a*h;p+=l>>>16;p+=d*b;var x=p>>>16;p=(p&65535)+e*h;x+=p>>>16;p=(p&65535)+a*g;x=x+(p>>>16)+(c*b+d*h+e*g+a*f)&65535;return K((l&65535)<<16|k&65535,x<<16|p&65535)},L=function(a,b){if(Ub(b))throw Error("g");if(0>a.a){if(M(a,Nb)){if(M(b,Qb)||M(b,Rb))return Nb;if(M(b,Nb))return Qb;var c=1;if(0==c)c=
a;else{var d=a.a;c=32>c?K(a.b>>>c|d<<32-c,d>>c):K(d>>c-32,0<=d?0:-1)}c=L(c,b);d=1;if(0!=d){var e=c.b;c=32>d?K(e<<d,c.a<<d|e>>>32-d):K(0,e<<d-32)}if(M(c,Ob))return 0>b.a?Qb:Rb;a=a.add(J(Tb(b,c)));return c.add(L(a,b))}return 0>b.a?L(J(a),J(b)):J(L(J(a),b))}if(Ub(a))return Ob;if(0>b.a)return M(b,Nb)?Ob:J(L(a,J(b)));for(d=Ob;0<=Vb(a,b);){c=Math.max(1,Math.floor(Sb(a)/Sb(b)));e=Math.ceil(Math.log(c)/Math.LN2);e=48>=e?1:Math.pow(2,e-48);for(var f=Pb(c),g=Tb(f,b);0>g.a||0<Vb(g,a);)c-=e,f=Pb(c),g=Tb(f,b);
Ub(f)&&(f=Qb);d=d.add(f);a=a.add(J(g))}return d};I.prototype.and=function(a){return K(this.b&a.b,this.a&a.a)};I.prototype.or=function(a){return K(this.b|a.b,this.a|a.a)};I.prototype.xor=function(a){return K(this.b^a.b,this.a^a.a)};
/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
/*

 Copyright 2013 Google Inc. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
var Wb=function(a){y.call(this,a)};w(Wb,y);var Xb=function(a){y.call(this,a)};w(Xb,Wb);
/*

 Copyright 2012 Google Inc. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
var Yb=function(a){var b=[];Ja(a,function(c){b.push(c>>>24&255);b.push(c>>>16&255);b.push(c>>>8&255);b.push(c&255)});return b},Zb=function(a){for(var b=1,c=0;c<a.length;c++){var d=a[c];b&=("number"==typeof d&&0<=d&&255>=d&&0==d-Math.floor(d))|0}return 1==b};
var $b=function(){this.a=null},ac=function(){this.a=null};w(ac,$b);
var bc=function(){};
/*

 Copyright 2014 Google Inc. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
var N=function(a,b){return(-(a>b|0)|0)&(a^b)^b};
/*

 Copyright 2011 Google Inc. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
var O=function(a){this.a=[];if(void 0!==a){if(!("function"==xa(r.Uint8Array)&&a instanceof Uint8Array||Zb(a)))throw new Xb("Input should be a byte array.");for(var b=a.length,c=Array((b+2)/3|0),d=0;0<=b;b-=3)c[d++]=a[b-1]&255|(a[b-2]&255)<<8|(a[b-3]&255)<<16;this.a=c}this.b=0},P=function(a){var b=new O;b.a.length=a;return b},cc=function(a){var b=new O;b.a=Oa(a);return b},dc=function(a){if(0>a||281474976710656<a)throw new Xb("Argument must be a valid integer.");var b=new O;do b.a.push(a&16777215),
a=Math.floor(a/16777216);while(0<a);return b},ec=function(a,b,c){c=-c|0;for(var d=N(a.a.length,b.a.length),e=P(d),f=0;f<d;++f)e.a[f]=c&(a.a[f]^b.a[f]);for(f=0;f<d;++f)e.a[f]^=b.a[f];return e},fc=function(a){for(var b=a.a.length,c=0,d=Array(3*b);0<b;--b)d[c++]=a.a[b-1]>>>16&255,d[c++]=a.a[b-1]>>>8&255,d[c++]=a.a[b-1]&255;for(c=b=a=0;c<d.length;++c)b|=d[c],a+=!b&!d[c];return d.slice(a-(1&!b))};
O.prototype.toString=function(){var a=[],b=this,c=dc(1E6);do b=gc(b,c),a.unshift(b.N.a[0]),b=b.U,hc(b);while(!ic(b));return a.map(function(d,e){return 0==e||1E6<d?""+d:("000000"+d).slice(-6)}).join("")};var hc=function(a){for(var b=0,c=0,d=a.a.length-1;0<d;--d)c|=a.a[d],b+=!c&!a.a[d];a.a.length-=b;return a},jc=function(a){if(0==a.b){for(var b=0,c=0,d=a.a.length-1;0<d;--d)c|=a.a[d],b+=!c&!a.a[d];c=a.a.length-b;b=24*c;c=a.a[c-1];for(c|=!c;0==(c&8388608);)c<<=1,--b;a=a.b=b}else a=a.b;return a};
O.prototype.add=function(a){for(var b=N(this.a.length,a.a.length),c=P(b+1),d=0,e=0;e<b;++e)d+=(this.a[e]|0)+(a.a[e]|0),c.a[e]=d&16777215,d>>=24;c.a[b]=d;return c};
var gc=function(a,b){var c=jc(b),d=(c+24-1)/24|0;c=24*d-c;b=kc(b,c);var e=ec(cc(a.a),kc(a,c),0==c|0);a=ec(lc,P(e.a.length+1),0>=e.a.length+1-d|0);e.a.push(0);for(var f=e.a.length-d-1;0<=f;f--){var g=b.a.length,h=16777216*e.a[g+f]+e.a[g+f-1];var k=b.a[g-1];var l=Math.floor(h/k);k=l-(16777216==l|l*(b.a[g-2]|0)>16777216*(h-l*k)+(e.a[g+f-2]|0));g=0;a.a[f]=k;for(h=0;h<=d;h++)g+=e.a[h+f]-(b.a[h]|0)*k,e.a[h+f]=g&16777215,g=Math.floor(g/16777216);k=g;g=0;a.a[f]+=k;for(h=0;h<=d;h++)g+=e.a[h+f]+(b.a[h]&k),
e.a[h+f]=g&16777215,g>>=24}if(0>c||23<c)throw new Xb("Illegal shift value.");h=e.a.length;b=P(h);f=(1<<c)-1;g=0;for(--h;0<=h;h--)b.a[h]=g+(e.a[h]>>c),g=(e.a[h]&f)<<24-c;c=P(d);for(e=0;e<d;e++)c.a[e]=b.a[e]|0;e=c;hc(a);return{U:a,N:e}},ic=function(a){for(var b=lc,c=0,d=0,e=0,f=0,g=N(a.a.length,b.a.length)-1;0<=g;--g){var h=a.a[g]|0,k=b.a[g]|0;d|=h<k;c|=h>k&!d;e|=h>k;f|=h<k&!e}return 0==c-f};
O.prototype.and=function(a){for(var b=N(this.a.length,a.a.length),c=P(b);0<=b;--b)c.a[b]=(this.a[b]|0)&(a.a[b]|0);return c};O.prototype.or=function(a){for(var b=N(this.a.length,a.a.length),c=P(b);0<=b;--b)c.a[b]=this.a[b]|0|a.a[b]|0;return c};O.prototype.xor=function(a){for(var b=N(this.a.length,a.a.length),c=P(b);0<=b;--b)c.a[b]=(this.a[b]|0)^(a.a[b]|0);return c};
var kc=function(a,b){if(0>b||23<b)throw new Xb("Illegal shift value.");for(var c=a.a.length,d=P(c+1),e=(1<<b)-1,f=(1<<24-b)-1,g=0,h=0;h<c;h++)d.a[h]=((a.a[h]&f)<<b)+g,g=a.a[h]>>24-b&e;d.a[c]=g;return hc(d)},lc=dc(0);dc(1);dc(2);
var nc=function(a,b){O.call(this,a);hc(this);a=1;for(var c=this.a[0],d=1;16777216>d;d<<=1)a*c&d&&(a|=d);this.f=16777216-a;if(void 0!==b)b=new O(b);else{b=this.a.length;a=P(2*b+1);for(c=0;c<2*b;++c)a.a[c]=0;a.a[2*b]=1;b=gc(a,this).N}this.g=b;this.c=mc(this,this.g)};w(nc,O);
nc.prototype.pow=function(a,b){a=new O(a);b instanceof O&&(b=fc(b));var c=Q(this,a,this.g);a=Array(16);a[0]=this.c;for(var d=1;16>d;++d)a[d]=Q(this,c,a[d-1]);c=P(this.a.length);d=cc(this.c.a);for(var e=b.length,f=0;f<e;++f)Q(this,d,d,c),Q(this,c,c,d),Q(this,d,d,c),Q(this,c,c,d),Q(this,d,a[b[f]>>4&15],c),Q(this,c,c,d),Q(this,d,d,c),Q(this,c,c,d),Q(this,d,d,c),Q(this,c,a[b[f]&15],d);mc(this,d,c);return fc(c)};
var mc=function(a,b,c){var d=a.a.length;c=c||P(d);for(var e=0;e<d;++e)c.a[e]=b.a[e];for(e=0;e<d;++e){b=a;var f=c,g=f.a[0],h=g*b.f&16777215;g+=h*b.a[0];for(var k=1,l=b.a.length;k<l;++k)g=(g/16777216|0)+f.a[k]+h*b.a[k],f.a[k-1]=g&16777215;f.a[k-1]=g/16777216|0}oc(a,c,d);return c},Q=function(a,b,c,d){var e=a.a.length;d=d||P(e);for(var f=0;f<e;++f)d.a[f]=0;for(f=0;f<e;++f){var g=a,h=b.a[f]|0,k=c,l=d,p=h*k.a[0]+l.a[0],x=(p&16777215)*g.f&16777215;p+=x*g.a[0];for(var F=1,Wd=g.a.length;F<Wd;++F)p=(p/16777216|
0)+h*(k.a[F]|0)+l.a[F]+x*g.a[F],l.a[F-1]=p&16777215;l.a[F-1]=p/16777216|0}oc(a,d,e);return d},oc=function(a,b,c){for(var d=0,e=0;e<c;++e)d+=b.a[e]-a.a[e],b.a[e]=d&16777215,d>>=24;var f=d>>24;for(e=d=0;e<c;++e)d+=b.a[e]+(a.a[e]&f),b.a[e]=d&16777215,d>>=24};
var pc=function(a,b,c){this.c=a;this.f=this.b=b;this.a=null;this.modulusLength=0;this.a=new nc(a,c);this.modulusLength=Math.ceil(jc(this.a)/8)};w(pc,bc);
var sc=function(a,b){this.b=64;this.h=r.Uint8Array?new Uint8Array(this.b):Array(this.b);this.i=this.f=0;this.a=[];this.l=a;this.j=b;this.o=r.Int32Array?new Int32Array(64):Array(64);void 0!==qc||(r.Int32Array?qc=new Int32Array(rc):qc=rc);this.reset()},qc;w(sc,Jb);var tc=Na(128,Qa(0,63));sc.prototype.reset=function(){this.i=this.f=0;this.a=r.Int32Array?new Int32Array(this.j):Oa(this.j)};
var uc=function(a){for(var b=a.h,c=a.o,d=0,e=0;e<b.length;)c[d++]=b[e]<<24|b[e+1]<<16|b[e+2]<<8|b[e+3],e=4*d;for(b=16;64>b;b++){e=c[b-15]|0;d=c[b-2]|0;var f=(c[b-16]|0)+((e>>>7|e<<25)^(e>>>18|e<<14)^e>>>3)|0,g=(c[b-7]|0)+((d>>>17|d<<15)^(d>>>19|d<<13)^d>>>10)|0;c[b]=f+g|0}d=a.a[0]|0;e=a.a[1]|0;var h=a.a[2]|0,k=a.a[3]|0,l=a.a[4]|0,p=a.a[5]|0,x=a.a[6]|0;f=a.a[7]|0;for(b=0;64>b;b++){var F=((d>>>2|d<<30)^(d>>>13|d<<19)^(d>>>22|d<<10))+(d&e^d&h^e&h)|0;g=l&p^~l&x;f=f+((l>>>6|l<<26)^(l>>>11|l<<21)^(l>>>
25|l<<7))|0;g=g+(qc[b]|0)|0;g=f+(g+(c[b]|0)|0)|0;f=x;x=p;p=l;l=k+g|0;k=h;h=e;e=d;d=g+F|0}a.a[0]=a.a[0]+d|0;a.a[1]=a.a[1]+e|0;a.a[2]=a.a[2]+h|0;a.a[3]=a.a[3]+k|0;a.a[4]=a.a[4]+l|0;a.a[5]=a.a[5]+p|0;a.a[6]=a.a[6]+x|0;a.a[7]=a.a[7]+f|0};
sc.prototype.c=function(a,b){void 0===b&&(b=a.length);var c=0,d=this.f;if(t(a))for(;c<b;)this.h[d++]=a.charCodeAt(c++),d==this.b&&(uc(this),d=0);else if(ya(a))for(;c<b;){var e=a[c++];if(!("number"==typeof e&&0<=e&&255>=e&&e==(e|0)))throw Error("i");this.h[d++]=e;d==this.b&&(uc(this),d=0)}else throw Error("j");this.f=d;this.i+=b};
sc.prototype.g=function(){var a=[],b=8*this.i;56>this.f?this.c(tc,56-this.f):this.c(tc,this.b-(this.f-56));for(var c=63;56<=c;c--)this.h[c]=b&255,b/=256;uc(this);for(c=b=0;c<this.l;c++)for(var d=24;0<=d;d-=8)a[b++]=this.a[c]>>d&255;return a};
var rc=[1116352408,1899447441,3049323471,3921009573,961987163,1508970993,2453635748,2870763221,3624381080,310598401,607225278,1426881987,1925078388,2162078206,2614888103,3248222580,3835390401,4022224774,264347078,604807628,770255983,1249150122,1555081692,1996064986,2554220882,2821834349,2952996808,3210313671,3336571891,3584528711,113926993,338241895,666307205,773529912,1294757372,1396182291,1695183700,1986661051,2177026350,2456956037,2730485921,2820302411,3259730800,3345764771,3516065817,3600352804,
4094571909,275423344,430227734,506948616,659060556,883997877,958139571,1322822218,1537002063,1747873779,1955562222,2024104815,2227730452,2361852424,2428436474,2756734187,3204031479,3329325298];
var wc=function(){sc.call(this,8,vc)};w(wc,sc);var vc=[1779033703,3144134277,1013904242,2773480762,1359893119,2600822924,528734635,1541459225];
for(var xc=[1116352408,3609767458,1899447441,602891725,3049323471,3964484399,3921009573,2173295548,961987163,4081628472,1508970993,3053834265,2453635748,2937671579,2870763221,3664609560,3624381080,2734883394,310598401,1164996542,607225278,1323610764,1426881987,3590304994,1925078388,4068182383,2162078206,991336113,2614888103,633803317,3248222580,3479774868,3835390401,2666613458,4022224774,944711139,264347078,2341262773,604807628,2007800933,770255983,1495990901,1249150122,1856431235,1555081692,3175218132,
1996064986,2198950837,2554220882,3999719339,2821834349,766784016,2952996808,2566594879,3210313671,3203337956,3336571891,1034457026,3584528711,2466948901,113926993,3758326383,338241895,168717936,666307205,1188179964,773529912,1546045734,1294757372,1522805485,1396182291,2643833823,1695183700,2343527390,1986661051,1014477480,2177026350,1206759142,2456956037,344077627,2730485921,1290863460,2820302411,3158454273,3259730800,3505952657,3345764771,106217008,3516065817,3606008344,3600352804,1432725776,4094571909,
1467031594,275423344,851169720,430227734,3100823752,506948616,1363258195,659060556,3750685593,883997877,3785050280,958139571,3318307427,1322822218,3812723403,1537002063,2003034995,1747873779,3602036899,1955562222,1575990012,2024104815,1125592928,2227730452,2716904306,2361852424,442776044,2428436474,593698344,2756734187,3733110249,3204031479,2999351573,3329325298,3815920427,3391569614,3928383900,3515267271,566280711,3940187606,3454069534,4118630271,4000239992,116418474,1914138554,174292421,2731055270,
289380356,3203993006,460393269,320620315,685471733,587496836,852142971,1086792851,1017036298,365543100,1126000580,2618297676,1288033470,3409855158,1501505948,4234509866,1607167915,987167468,1816402316,1246189591],yc=[],zc=0;zc<xc.length;zc+=2)yc.push(new I(xc[zc+1],xc[zc]));
var Ac=function(){this.b=-1};w(Ac,Jb);Ac.prototype.reset=function(){this.a.reset()};Ac.prototype.g=function(){return this.a.g()};Ac.prototype.c=function(a,b){this.a.c(a,b)};Ac.prototype.hash=function(a){this.reset();this.c(a);return this.g()};
var Bc=function(){this.b=-1;this.a=new wc;this.b=this.a.b};ma(Bc,Ac);Bc.prototype.f="SHA256";
var Cc=function(a){y.call(this,a)};ma(Cc,y);
var Dc={MD5:[48,32,48,12,6,8,42,134,72,134,247,13,2,5,5,0,4,16],RIPEMD160:[48,33,48,9,6,5,43,36,3,2,1,5,0,4,20],SHA1:[48,33,48,9,6,5,43,14,3,2,26,5,0,4,20],SHA224:[48,45,48,13,6,9,96,134,72,1,101,3,4,2,4,5,0,4,28],SHA256:[48,49,48,13,6,9,96,134,72,1,101,3,4,2,1,5,0,4,32],SHA384:[48,65,48,13,6,9,96,134,72,1,101,3,4,2,2,5,0,4,48],SHA512:[48,81,48,13,6,9,96,134,72,1,101,3,4,2,3,5,0,4,64]};
var Ec=function(a,b,c,d){pc.call(this,a,b,c);this.g=d||new Bc};w(Ec,pc);
var Fc=function(a,b,c,d){this.a=null;this.b=new Ec(a,b,c,d)};w(Fc,ac);
var Gc=function(a){this.a=a};
var Hc=function(a,b){this.a=new Gc(new Fc(a,b))};
var Ic=function(a,b,c,d,e){this.a="U";this.b=0;this.c=!!a;a&&(a=a.split(","))&&2==a.length&&(this.a=a[0],this.b=parseInt(a[1],10));if(0>=b||0>=c||0>=d)throw Error("k");this.i=b;this.f=c;this.h=d;this.g=e},Jc=function(a){switch(a.a){case "Y":return a.i;case "N":return a.f;case "P":return a.g;default:return a.h}},Kc=function(a,b,c,d,e,f){this.g=new Hc(ub(a),ub(b));this.f=c;this.a=d;this.c=e;this.b=f},Lc=function(a,b,c){for(var d=a.g,e=[],f=0,g=0;g<c.length;g++){var h=c.charCodeAt(g);255<h&&(e[f++]=
h&255,h>>=8);e[f++]=h}b=ub(b.substr(b.indexOf(":")+1));d=d.a;c=d.a;c.a||(f=new Kb,f.c(Yb([c.b.c.length])),f.c(c.b.c),f.c(Yb([c.b.b.length])),f.c(c.b.b),f=f.g(),g=Array(5),g[0]=0,g[1]=f[0],g[2]=f[1],g[3]=f[2],g[4]=f[3],c.a=g);c=c.a;b:if(f=z(b,0,c.length),ya(c)&&ya(f)&&c.length==f.length){g=c.length;for(h=0;h<g;h++)if(c[h]!==f[h]){f=!1;break b}f=!0}else f=!1;if(f){f=c.length+4;c=z(b,c.length,f);g=[];for(h=0;h<c.length;h+=4)g.push((c[h+3]|c[h+2]<<8|c[h+1]<<16|c[h]<<24)>>>0);h=g[0];if(f+h>b.length)e=
null;else{c=z(b,f,f+h);g=Ra(c,Yb([e.length]),e,b[0]);d=d.a.b;e=d.a.pow(z(b,f+h),d.f);b=d.g;d=d.modulusLength-1;g=b.hash(g);f=[];if(void 0===Dc[b.f])throw new Cc("invalid hash for signature");Pa(f,Dc[b.f]);Pa(f,g);b=f.length;if(d<b+11)throw new Cc("intended encoded message length too short");b=[1].concat(Qa(255,d-b-3+1),[0],f);if(b.length===e.length&&Zb(b)&&Zb(e)){d=1;for(f=0;f<b.length;f++)d&=!(b[f]^e[f])|0;e=1==d}else e=!1;e=e?c:null}}else e=null;if(e)if(8192>=e.length)e=String.fromCharCode.apply(null,
e);else{b="";for(d=0;d<e.length;d+=8192)b+=String.fromCharCode.apply(null,z(e,d,d+8192));e=b}else e=null;return new Ic(e,a.f,a.a,a.c,a.b)};
var ba=function(a){Db(this,a,null)};w(ba,H);
var Mc=function(a){var b=r.location.hostname;a=ea(a);for(var c=a.next();!c.done;c=a.next()){c=c.value;var d;if(!(d=b.toLowerCase()==c.toLowerCase())){var e="."+c;d=String(e).toLowerCase();e=String(b.substr(b.length-e.length,e.length)).toLowerCase();d=0==(d<e?-1:d==e?0:1)}if(d)return"."+c}return null};
var Nc=function(){this.a=document||{cookie:""}};Nc.prototype.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error("m`"+a);if(/[;\r\n]/.test(b))throw Error("n`"+b);void 0!==c||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(Ea()+1E3*c)).toUTCString();this.a.cookie=a+"="+b+e+d+c+f};
Nc.prototype.get=function(a,b){for(var c=a+"=",d=(this.a.cookie||"").split(";"),e=0,f;e<d.length;e++){f=Ua(d[e]);if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};Nc.prototype.s=function(){return Oc(this).keys};Nc.prototype.f=function(){return Oc(this).values};
var Oc=function(a){a=(a.a.cookie||"").split(";");for(var b=[],c=[],d,e,f=0;f<a.length;f++)e=Ua(a[f]),d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};
var Pc=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/,Qc=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}},Rc=/#|$/;
var Sc=function(a,b,c){this.b=a;this.f=n(b,6);this.a=n(b,1);this.c=c;a=r.location.href;c=n(b,7);a:{for(var d=a.search(Rc),e=0,f=c.length;0<=(e=a.indexOf(c,e))&&e<d;){var g=a.charCodeAt(e-1);if(38==g||63==g)if(g=a.charCodeAt(e+f),!g||61==g||38==g||35==g){a=e;break a}e+=f+1}a=-1}this.h=0<=a;this.g=new Kc(n(b,5),n(b,4),n(b,8),n(b,9),n(b,10),n(b,11))},Tc=function(a){var b=a.b.get(a.a);if(null!==a.c&&b&&(b=Lc(a.g,b,a.f),"Y"==b.a)){if(b.b+Jc(b)<Ea()){b=a.b;var c=a.a;a=a.c;b.get(c);b.set(c,"",0,"/",a)}return!0}return!1},
Uc=function(a){if(null!==a.c){if(a.h)return!0;var b=a.b.get(a.a);return b?(a=Lc(a.g,b,a.f),a.b+Jc(a)<Ea()||"P"==a.a||!a.c):!0}return!1};
var Wc=function(a){Db(this,a,Vc)};w(Wc,H);var Fb=function(a){Db(this,a,null)};w(Fb,H);var Vc=[1];
var Xc=function(a){Db(this,a,null)};w(Xc,H);var Yc=function(a){a.a||(a.a={});if(2 in a.a)a=a.a[2];else{var b=n(a,2);if(!b){var c=b=[];2<a.g?a.b[2+a.f]=c:(Cb(a),a.c[2]=c)}a=a.a[2]=new E(b)}return a};
var Zc;(Zc=!D)||(Zc=9<=Number(ob));var $c=Zc,ad=D&&!nb("9"),bd=function(){if(!r.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{r.addEventListener("test",wa,b),r.removeEventListener("test",wa,b)}catch(c){}return a}();
var cd=function(){this.g=this.g;this.i=this.i};cd.prototype.g=!1;cd.prototype.c=function(){if(this.i)for(;this.i.length;)this.i.shift()()};
var R=function(a,b){this.type=a;this.a=this.target=b;this.O=!0};R.prototype.b=function(){this.O=!1};
var ed=function(a,b){R.call(this,a?a.type:"");this.relatedTarget=this.a=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.pointerId=0;this.pointerType="";this.c=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.a=b;if(b=a.relatedTarget){if(fb){a:{try{ab(b.nodeName);var e=!0;break a}catch(f){}e=!1}e||(b=
null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=
a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType=t(a.pointerType)?a.pointerType:dd[a.pointerType]||"";this.c=a;a.defaultPrevented&&this.b()}};w(ed,R);var dd={2:"touch",3:"pen",4:"mouse"};ed.prototype.b=function(){ed.F.b.call(this);var a=this.c;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,ad)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var fd="closure_listenable_"+(1E6*Math.random()|0),gd=function(a){return!(!a||!a[fd])},hd=0;
var id=function(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.capture=!!d;this.K=e;this.key=++hd;this.u=this.J=!1},jd=function(a){a.u=!0;a.listener=null;a.a=null;a.src=null;a.K=null};
var kd=function(a){this.src=a;this.a={};this.b=0};kd.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var g=ld(a,b,d,e);-1<g?(b=a[g],c||(b.J=!1)):(b=new id(b,this.src,f,!!d,e),b.J=c,a.push(b));return b};
var md=function(a,b){var c=b.type;if(!(c in a.a))return!1;var d=Ma(a.a[c],b);d&&(jd(b),0==a.a[c].length&&(delete a.a[c],a.b--));return d},nd=function(a,b){b=b&&b.toString();var c=0,d;for(d in a.a)if(!b||d==b){for(var e=a.a[d],f=0;f<e.length;f++)++c,jd(e[f]);delete a.a[d];a.b--}},ld=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.u&&f.listener==b&&f.capture==!!c&&f.K==d)return e}return-1};
var od="closure_lm_"+(1E6*Math.random()|0),pd={},qd=0,sd=function(a,b,c,d,e){if(d&&d.once)return rd(a,b,c,d,e);if(u(b)){for(var f=0;f<b.length;f++)sd(a,b[f],c,d,e);return null}c=td(c);return gd(a)?a.m.add(String(b),c,!1,za(d)?!!d.capture:!!d,e):ud(a,b,c,!1,d,e)},ud=function(a,b,c,d,e,f){if(!b)throw Error("o");var g=za(e)?!!e.capture:!!e,h=vd(a);h||(a[od]=h=new kd(a));c=h.add(b,c,d,g,f);if(c.a)return c;d=wd();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)bd||(e=g),void 0===e&&(e=!1),a.addEventListener(b.toString(),
d,e);else if(a.attachEvent)a.attachEvent(xd(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("p");qd++;return c},wd=function(){var a=yd,b=$c?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b},rd=function(a,b,c,d,e){if(u(b)){for(var f=0;f<b.length;f++)rd(a,b[f],c,d,e);return null}c=td(c);return gd(a)?a.m.add(String(b),c,!0,za(d)?!!d.capture:!!d,e):ud(a,b,c,!0,d,e)},zd=function(a,b,c,d,e){if(u(b))for(var f=
0;f<b.length;f++)zd(a,b[f],c,d,e);else(d=za(d)?!!d.capture:!!d,c=td(c),gd(a))?(a=a.m,b=String(b).toString(),b in a.a&&(f=a.a[b],c=ld(f,c,d,e),-1<c&&(jd(f[c]),Array.prototype.splice.call(f,c,1),0==f.length&&(delete a.a[b],a.b--)))):a&&(a=vd(a))&&(b=a.a[b.toString()],a=-1,b&&(a=ld(b,c,d,e)),(c=-1<a?b[a]:null)&&Ad(c))},Ad=function(a){if("number"==typeof a||!a||a.u)return!1;var b=a.src;if(gd(b))return md(b.m,a);var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?
b.detachEvent(xd(c),d):b.addListener&&b.removeListener&&b.removeListener(d);qd--;(c=vd(b))?(md(c,a),0==c.b&&(c.src=null,b[od]=null)):jd(a);return!0},xd=function(a){return a in pd?pd[a]:pd[a]="on"+a},Cd=function(a,b,c,d){var e=!0;if(a=vd(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.u&&(f=Bd(f,d),e=e&&!1!==f)}return e},Bd=function(a,b){var c=a.listener,d=a.K||a.src;a.J&&Ad(a);return c.call(d,b)},yd=function(a,b){if(a.u)return!0;if(!$c){if(!b)a:{b=["window",
"event"];for(var c=r,d=0;d<b.length;d++)if(c=c[b[d]],null==c){b=null;break a}b=c}d=b;b=new ed(d,this);c=!0;if(!(0>d.keyCode||void 0!=d.returnValue)){a:{var e=!1;if(0==d.keyCode)try{d.keyCode=-1;break a}catch(g){e=!0}if(e||void 0==d.returnValue)d.returnValue=!0}d=[];for(e=b.a;e;e=e.parentNode)d.push(e);a=a.type;for(e=d.length-1;0<=e;e--){b.a=d[e];var f=Cd(d[e],a,!0,b);c=c&&f}for(e=0;e<d.length;e++)b.a=d[e],f=Cd(d[e],a,!1,b),c=c&&f}return c}return Bd(a,new ed(b,this))},vd=function(a){a=a[od];return a instanceof
kd?a:null},Dd="__closure_events_fn_"+(1E9*Math.random()>>>0),td=function(a){if("function"==xa(a))return a;a[Dd]||(a[Dd]=function(b){return a.handleEvent(b)});return a[Dd]};
var Ed=function(){this.a=r.document||document};
var Fd=function(){return gb?"Webkit":fb?"Moz":D?"ms":db?"O":null},Gd=function(a,b){if(b&&a in b)return a;var c=Fd();return c?(c=c.toLowerCase(),a=c+$a(a),void 0===b||a in b?a:null):null};
var S=function(){cd.call(this);this.m=new kd(this);this.P=this;this.H=null};w(S,cd);S.prototype[fd]=!0;S.prototype.removeEventListener=function(a,b,c,d){zd(this,a,b,c,d)};
var T=function(a,b){var c,d=a.H;if(d)for(c=[];d;d=d.H)c.push(d);a=a.P;d=b.type||b;if(t(b))b=new R(b,a);else if(b instanceof R)b.target=b.target||a;else{var e=b;b=new R(d,a);Ta(b,e)}e=!0;if(c)for(var f=c.length-1;0<=f;f--){var g=b.a=c[f];e=Hd(g,d,!0,b)&&e}g=b.a=a;e=Hd(g,d,!0,b)&&e;e=Hd(g,d,!1,b)&&e;if(c)for(f=0;f<c.length;f++)g=b.a=c[f],e=Hd(g,d,!1,b)&&e};S.prototype.c=function(){S.F.c.call(this);this.m&&nd(this.m,void 0);this.H=null};
var Hd=function(a,b,c,d){b=a.m.a[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.u&&g.capture==c){var h=g.listener,k=g.K||g.src;g.J&&md(a.m,g);e=!1!==h.call(k,d)&&e}}return e&&0!=d.O};
var Jd=function(a){var b=Id;return function(){var c=this||r;c=c.closure_memoize_cache_||(c.closure_memoize_cache_={});var d=b(a[Aa]||(a[Aa]=++Ba),arguments);return c.hasOwnProperty(d)?c[d]:c[d]=a.apply(this,arguments)}},Id=function(a,b){a=[a];for(var c=b.length-1;0<=c;--c)a.push(typeof b[c],b[c]);return a.join("\x0B")};
var U=function(a){S.call(this);a||(a=Ha||(Ha=new Ed));this.a=a;if(this.f=this.j())this.h=sd(this.a.a,this.f,v(this.o,this))};w(U,S);U.prototype.j=Jd(function(){var a=!!this.b(),b="hidden"!=this.b();if(a){var c;b?c=((Fd()||"")+"visibilitychange").toLowerCase():c="visibilitychange";a=c}else a=null;return a});U.prototype.b=Jd(function(){return Gd("hidden",this.a.a)});U.prototype.l=Jd(function(){return Gd("visibilityState",this.a.a)});var Kd=function(a){return!!a.a.a[a.b()]};
U.prototype.o=function(){var a=this.b()?this.a.a[this.l()]:null;a=new Ld(Kd(this),a);T(this,a)};U.prototype.c=function(){Ad(this.h);U.F.c.call(this)};var Ld=function(){R.call(this,"visibilitychange")};w(Ld,R);
var Md=function(){};Md.prototype.a=null;var Od=function(a){var b;(b=a.a)||(b={},Nd(a)&&(b[0]=!0,b[1]=!0),b=a.a=b);return b};
var Pd,Qd=function(){};w(Qd,Md);var Rd=function(a){return(a=Nd(a))?new ActiveXObject(a):new XMLHttpRequest},Nd=function(a){if(!a.b&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.b=d}catch(e){}}throw Error("q");}return a.b};Pd=new Qd;
var V=function(a,b){this.b={};this.a=[];this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("r");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof V)for(c=a.s(),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])};V.prototype.f=function(){Sd(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};V.prototype.s=function(){Sd(this);return this.a.concat()};
var Sd=function(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];W(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){var e={};for(c=b=0;b<a.a.length;)d=a.a[b],W(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};V.prototype.get=function(a,b){return W(this.b,a)?this.b[a]:b};V.prototype.set=function(a,b){W(this.b,a)||(this.c++,this.a.push(a));this.b[a]=b};V.prototype.forEach=function(a,b){for(var c=this.s(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};
var W=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
var Td=function(a,b,c){if("function"==xa(a))c&&(a=v(a,c));else if(a&&"function"==typeof a.handleEvent)a=v(a.handleEvent,a);else throw Error("s");return 2147483647<Number(b)?-1:r.setTimeout(a,b||0)};
var X=function(a){S.call(this);this.headers=new V;this.o=a||null;this.b=!1;this.l=this.a=null;this.G="";this.f=this.A=this.h=this.v=!1;this.B=0;this.j=null;this.L="";this.C=this.D=!1};w(X,S);var Ud=/^https?$/i,Vd=["POST","PUT"],Xd=[],Zd=function(a,b,c){var d=new X;Xd.push(d);b&&d.m.add("complete",b,!1,void 0,void 0);d.m.add("ready",d.R,!0,void 0,void 0);d.D=!0;Yd(d,a,c)};X.prototype.R=function(){this.g||(this.g=!0,this.c());Ma(Xd,this)};
var Yd=function(a,b,c){if(a.a)throw Error("t`"+a.G+"`"+b);c=c?c.toUpperCase():"GET";a.G=b;a.v=!1;a.b=!0;a.a=a.o?Rd(a.o):Rd(Pd);a.l=a.o?Od(a.o):Od(Pd);a.a.onreadystatechange=v(a.I,a);try{a.A=!0,a.a.open(c,String(b),!0),a.A=!1}catch(f){$d(a);return}b=new V(a.headers);var d=La(b.s()),e=r.FormData&&!1;!(0<=Ia(Vd,c))||d||e||b.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");b.forEach(function(f,g){this.a.setRequestHeader(g,f)},a);a.L&&(a.a.responseType=a.L);"withCredentials"in a.a&&
a.a.withCredentials!==a.D&&(a.a.withCredentials=a.D);try{ae(a),0<a.B&&(a.C=be(a.a),a.C?(a.a.timeout=a.B,a.a.ontimeout=v(a.M,a)):a.j=Td(a.M,a.B,a)),a.h=!0,a.a.send(""),a.h=!1}catch(f){$d(a)}},be=function(a){return D&&nb(9)&&"number"==typeof a.timeout&&void 0!==a.ontimeout},Ka=function(a){return"content-type"==a.toLowerCase()};X.prototype.M=function(){"undefined"!=typeof va&&this.a&&(T(this,"timeout"),this.abort(8))};
var $d=function(a){a.b=!1;a.a&&(a.f=!0,a.a.abort(),a.f=!1);ce(a);de(a)},ce=function(a){a.v||(a.v=!0,T(a,"complete"),T(a,"error"))};X.prototype.abort=function(){this.a&&this.b&&(this.b=!1,this.f=!0,this.a.abort(),this.f=!1,T(this,"complete"),T(this,"abort"),de(this))};X.prototype.c=function(){this.a&&(this.b&&(this.b=!1,this.f=!0,this.a.abort(),this.f=!1),de(this,!0));X.F.c.call(this)};X.prototype.I=function(){this.g||(this.A||this.h||this.f?ee(this):this.S())};X.prototype.S=function(){ee(this)};
var ee=function(a){if(a.b&&"undefined"!=typeof va&&(!a.l[1]||4!=(a.a?a.a.readyState:0)||2!=fe(a)))if(a.h&&4==(a.a?a.a.readyState:0))Td(a.I,0,a);else if(T(a,"readystatechange"),4==(a.a?a.a.readyState:0)){a.b=!1;try{ge(a)?(T(a,"complete"),T(a,"success")):ce(a)}finally{de(a)}}},de=function(a,b){if(a.a){ae(a);var c=a.a,d=a.l[0]?wa:null;a.a=null;a.l=null;b||T(a,"ready");try{c.onreadystatechange=d}catch(e){}}},ae=function(a){a.a&&a.C&&(a.a.ontimeout=null);a.j&&(r.clearTimeout(a.j),a.j=null)},ge=function(a){var b=
fe(a);a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}if(!c){if(b=0===b)a=String(a.G).match(Pc)[1]||null,!a&&r.self&&r.self.location&&(a=r.self.location.protocol,a=a.substr(0,a.length-1)),b=!Ud.test(a?a.toLowerCase():"");c=b}return c},fe=function(a){try{return 2<(a.a?a.a.readyState:0)?a.a.status:-1}catch(b){return-1}};
var m=function(a,b){this.g=this.j=this.f="";this.i=null;this.h=this.c="";this.b=!1;if(a instanceof m){this.b=void 0!==b?b:a.b;he(this,a.f);this.j=a.j;this.g=a.g;ie(this,a.i);this.c=a.c;b=a.a;var c=new Y;c.c=b.c;b.a&&(c.a=new V(b.a),c.b=b.b);je(this,c);this.h=a.h}else a&&(c=String(a).match(Pc))?(this.b=!!b,he(this,c[1]||"",!0),this.j=ke(c[2]||""),this.g=ke(c[3]||"",!0),ie(this,c[4]),this.c=ke(c[5]||"",!0),je(this,c[6]||"",!0),this.h=ke(c[7]||"")):(this.b=!!b,this.a=new Y(null,this.b))};
m.prototype.toString=function(){var a=[],b=this.f;b&&a.push(le(b,me,!0),":");var c=this.g;if(c||"file"==b)a.push("//"),(b=this.j)&&a.push(le(b,me,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.i,null!=c&&a.push(":",String(c));if(c=this.c)this.g&&"/"!=c.charAt(0)&&a.push("/"),a.push(le(c,"/"==c.charAt(0)?ne:oe,!0));(c=this.a.toString())&&a.push("?",c);(c=this.h)&&a.push("#",le(c,pe));return a.join("")};
var he=function(a,b,c){a.f=c?ke(b,!0):b;a.f&&(a.f=a.f.replace(/:$/,""))},ie=function(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("u`"+b);a.i=b}else a.i=null},je=function(a,b,c){b instanceof Y?(a.a=b,qe(a.a,a.b)):(c||(b=le(b,re)),a.a=new Y(b,a.b))},ke=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},le=function(a,b,c){return t(a)?(a=encodeURI(a).replace(b,se),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null},se=function(a){a=a.charCodeAt(0);return"%"+
(a>>4&15).toString(16)+(a&15).toString(16)},me=/[#\/\?@]/g,oe=/[#\?:]/g,ne=/[#\?]/g,re=/[#\?@]/g,pe=/#/g,Y=function(a,b){this.b=this.a=null;this.c=a||null;this.g=!!b},Z=function(a){a.a||(a.a=new V,a.b=0,a.c&&Qc(a.c,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))};Y.prototype.add=function(a,b){Z(this);this.c=null;a=te(this,a);var c=this.a.get(a);c||this.a.set(a,c=[]);c.push(b);this.b+=1;return this};
var ue=function(a,b){Z(a);b=te(a,b);W(a.a.b,b)&&(a.c=null,a.b-=a.a.get(b).length,a=a.a,W(a.b,b)&&(delete a.b[b],a.c--,a.a.length>2*a.c&&Sd(a)))},ve=function(a,b){Z(a);b=te(a,b);return W(a.a.b,b)};Y.prototype.forEach=function(a,b){Z(this);this.a.forEach(function(c,d){Ja(c,function(e){a.call(b,e,d,this)},this)},this)};Y.prototype.s=function(){Z(this);for(var a=this.a.f(),b=this.a.s(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};
Y.prototype.f=function(a){Z(this);var b=[];if(t(a))ve(this,a)&&(b=Na(b,this.a.get(te(this,a))));else{a=this.a.f();for(var c=0;c<a.length;c++)b=Na(b,a[c])}return b};Y.prototype.set=function(a,b){Z(this);this.c=null;a=te(this,a);ve(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b+=1;return this};Y.prototype.get=function(a,b){if(!a)return b;a=this.f(a);return 0<a.length?String(a[0]):b};
Y.prototype.toString=function(){if(this.c)return this.c;if(!this.a)return"";for(var a=[],b=this.a.s(),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.f(d);for(var f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+encodeURIComponent(String(d[f])));a.push(g)}}return this.c=a.join("&")};
var te=function(a,b){b=String(b);a.g&&(b=b.toLowerCase());return b},qe=function(a,b){b&&!a.g&&(Z(a),a.c=null,a.a.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(ue(this,d),ue(this,e),0<c.length&&(this.c=null,this.a.set(te(this,e),Oa(c)),this.b+=c.length))},a));a.g=b};
/*

Math.uuid.js (v1.4)
http://www.broofa.com
mailto:robert@broofa.com
Copyright (c) 2010 Robert Kieffer
Dual licensed under the MIT and GPL licenses.
*/
var we="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".split(""),xe=function(){for(var a=Array(36),b=0,c,d=0;36>d;d++)8==d||13==d||18==d||23==d?a[d]="-":14==d?a[d]="4":(2>=b&&(b=33554432+16777216*Math.random()|0),c=b&15,b>>=4,a[d]=we[19==d?c&3|8:c]);return a.join("")};
var ye=function(a){var b=Eb(a,Ib,1);this.a=new U;this.o=new MutationObserver(this.i.bind(this));this.b=null;this.h=this.g=!1;this.l=new Nc;this.H=n(b,1);this.G=n(b,13);this.v=(this.c=Mc(yb(Yc(a)).map(function(c){return c[0]})))?Yc(a).get(aa(this.c)):new ba;this.f=new Sc(this.l,b,this.c);this.I=Gb(Eb(a,Wc,3));this.B=xe();this.j=ca(n(a,4),this.v,"checksub");this.D=ca(n(a,4),this.v,"clientevent")};ye.prototype.start=function(){Tc(this.f)&&ze(this);Uc(this.f)&&Ae(this)};
ye.prototype.reset=function(){this.b=null;this.h=this.g=!1;var a=this.a;if(a)if(gd(a))a.m&&nd(a.m,"visibilitychange");else if(a=vd(a)){var b=0,c="visibilitychange".toString(),d;for(d in a.a)if(!c||d==c)for(var e=a.a[d].concat(),f=0;f<e.length;++f)Ad(e[f])&&++b}this.o.disconnect()};
var ze=function(a){try{a.o.observe(document.documentElement,{attributes:!0,childList:!0,subtree:!0})}catch(b){}a.i();a.a&&a.a.b()?(sd(a.a,"visibilitychange",a.A,!1,a),Kd(a.a)||Be(a)):a.h||(Ce(a,3),a.h=!0)},Ae=function(a){Zd(a.j,function(b){var c=Tc(a.f);ge(b.target)&&(De(a,b),Tc(a.f)&&!c&&ze(a))},"GET")},Ee=function(a){Zd(a.j,function(b){return De(a,b)},"GET")},De=function(a,b){b=b.target;try{var c=b.a?b.a.responseText:""}catch(d){c=""}a.l.set(a.H,c,a.G,"/",a.c)};
ye.prototype.i=function(){for(var a=ea(this.I),b=a.next();!b.done;b=a.next()){b=b.value;var c=n(b,1);if(c){c=document.querySelectorAll(c);for(var d=0;d<c.length;d++)if(1==n(b,2)){var e=c[d];e&&e.parentNode&&e.parentNode.removeChild(e)}}}};ye.prototype.A=function(){Kd(this.a)?null!=this.b&&(r.clearTimeout(this.b),this.b=null):Be(this)};
var Be=function(a){a.g||(Ce(a,1),a.g=!0);null==a.b&&(a.b=Td(a.C,1E3,a))},Ce=function(a,b){var c=new m(a.D);c.a.set("pageviewid",a.B);c.a.set("refererurl",r.location.href);c.a.set("type",b);Zd(c,1==b?function(d){ge(d.target)||Ee(a)}:null,"POST")};ye.prototype.C=function(){Ce(this,2);zd(this.a,"visibilitychange",this.A,!1,this)};
(function(a,b){r[a]=function(c){for(var d=[],e=0;e<arguments.length;++e)d[e]=arguments[e];r[a]=wa;b.apply(null,d)}})("__906a641ff040__",function(a){a=tb(a);a=new Xc(a?JSON.parse(a):null);(new ye(a)).start()});

}catch(e){_._DumpException(e)}
}).call(this,this.default_ContributorTargetingClientJs);
// Google Inc.

//# sourceURL=/_/mss/boq-content-ads-contributor/_/js/k=boq-content-ads-contributor.ContributorTargetingClientJs.en_US.xg4yGD7mK6k.es5.O/d=1/rs=AJlcJMwVEvH6o4Ed8ATTmWFds4z1IHX31w/m=contributor
window.__906a641ff040__('W1siQ1VJRCIsMjAwLDMsIkFRQUIiLCJ4akQrM24vMmRnOWY1VUZBSVVmKzR2aFpHUVNjM0VLaGRldHdhMjdkVjBMTGI3WmF6N3dCRi9TWGd0Tkw4MGZqdHlzK3BqZ2E1Y1oraFRneGlESGJKazZZc1hkdm4zUkZqQzBub3V4aHoraWwrcWxCcElHSkVUbmFDeEZ0ZFFxWjZ3VnR1ZVE2NGtZN0JDTFhkcGs3ZmJIZndXYTJnT2FmRTRjVmduNVh0ekVubWlMSExRSE0rN1RVL2lyQnhMcCtLa0NSSmxSV2t0c09Vc2VsZnRsZGFUbzQzUWc4Rk5acVBZbjJaUy9aMjEvMWREdThJaDVHU0NNSVVMNTNnclJYQ0ticWg4b1N1akpiQ1RjQlFYMW9XUVc3eWQvRlNUdDlmRDhHSDg1TFVsa2h0d1hCZHFyZGtnMm9UVkRxeGpYR3dac2Y2QWZMYjNJNDJPdllZakpIbVFcdTAwM2RcdTAwM2QiLCI1NjJkNzUwNzQwNDIzNzc3IiwicmVmY29uIiw5MDAwMDAsNjAwMDAsNjAwMDAsODY0MDAwMDAsIlAsMTU2Nzk1NTUxMDcyMDpBTEhHTHVRQUFBQVBVQ3d4TlRZM09UVTFOVEV3TnpJd0tRZ1V4T3Q2WHRFT3BOZ2lGN29PRGROd0o4RENDMGp3WDkrOXVtWmpnRVJkZEFhVEZTcmwvNTZqTHc5VGNRczdTa3gzY1NzNk1UWURNWWlqaW5ieXAxVWxFK2taYy8ycmRoSk13anpxb2Vwd2ozS1A3aHZWRjYwYmprbDBYQTdwTUhMTUtyaXZaWHhWVm54MVQxOXhnblg5aWdIbm1Yb0JGZGV0RzY4Rnh2dnNNd3BrWlZXOHQ4cWliMXROY053Nis1TmJvdUN4d0pacFB4QXVCK0ZZUklSYTZQTFZVOGJuTzR5d2RTUG42M21Vem1oampJNTlvWjBKSUEvM3d1YVdqTXJPNkx4Q2ZkSU9kOU12VmlIbmpWTGhqOXZzWEI1Vit6OEpzWEIzU1Jxek42cGQ4VytvN2UxUW4xcnpBaG5idGllRTJzNUlpVzRvU241bUpjT0VJQVx1MDAzZFx1MDAzZCIsMjU5MjAwMF0KLFtbImdydWJzdHJlZXQuY29tIixbIjU2MmQ3NTA3NDA0MjM3NzciXQpdCl0KLFtbWyIuYWQtY2hvaWNlcyIsMV0KLFsiLmFkLXNwbGFzaCIsMV0KLFsiaWZyYW1lW2lkXlx1MDAzZFwiZ29vZ2xlX2Fkc19pZnJhbWVcIl0iLDFdCixbIi5hZC13cmFwcGVyIiwxXQosWyIudHJjX3Jib3ggLnN5bmRpY2F0ZWRJdGVtIiwxXQosWyIudHJjX3Jib3hfYm9yZGVyX2VsbSAuc3luZGljYXRlZEl0ZW0iLDFdCixbIi50cmNfcmJveF9kaXYgLnN5bmRpY2F0ZWRJdGVtIiwxXQosWyIudHJjX3JlbGF0ZWRfY29udGFpbmVyIGRpdltkYXRhLWl0ZW0tc3luZGljYXRlZFx1MDAzZFwidHJ1ZVwiXSIsMV0KLFsiI2FkLXNwbGFzaCIsMV0KLFsiLmFkMjYweDYwIiwxXQosWyIuZmVlZC1hZCIsMV0KLFsiYVtocmVmXlx1MDAzZFwiaHR0cHM6Ly9hZC5kb3VibGVjbGljay5uZXQvXCJdIiwxXQosWyIuYWQiLDFdCixbImRpdltpZF5cdTAwM2RcImdvb2dsZV9hZHNfaWZyYW1lX1wiXSIsMV0KLFsiLnNwb25zb3ItbG9nbyIsMV0KLFsiLnRyYy1jb250ZW50LXNwb25zb3JlZCIsMV0KLFsiZGl2W2lkXlx1MDAzZFwiYWQtY2lkLVwiXSIsMV0KLFsiLmxhdGVzdC1hZCIsMV0KXQpdCiwiaHR0cHM6Ly9jb250cmlidXRvci5nb29nbGUuY29tL3NjcmlwdHMiXQo\x3d');